name: GitHub Actions Demo
on: [push]
jobs:
  lint-changelog:
    name: Lint changelog file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: lint files
      uses: avto-dev/markdown-lint@v1
      with:
        args: 'README.md'

#    - name: Lint changelog file
#      uses: docker://avtodev/markdown-lint:v1 # fastest way
#      with:
#        rules: '/lint/rules/changelog.js'
#        config: '/lint/config/changelog.yml'
#        args: './CHANGELOG.md'
#        ignore: './one_file.md ./another_file.md' # multiple files must be separated with single space

#    - name: Lint changelog file
#      uses: avto-dev/markdown-lint@v1
#      with:
#        rules: '/lint/rules/changelog.js'
#        config: '/lint/config/changelog.yml'
#        args: './CHANGELOG.md'
